create table USER (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  FIRST_NAME varchar(100),
  LAST_NAME varchar(100),
  MOBILE varchar(12) NOT NULL,
  EMAIL varchar(255),
  OTP_VERIFIED tinyint DEFAULT 0,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID)
);

insert into USER (FIRST_NAME, LAST_NAME, MOBILE, EMAIL) 
values ('GANESH','Jadhav','9920566922','ganesh@ganesh.com');

create table PRODUCT_CATEGORY_TYPE (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  TYPE varchar(100),
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID)
);

insert into PRODUCT_CATEGORY_TYPE (TYPE) 
values ('Material');

insert into PRODUCT_CATEGORY_TYPE (TYPE) 
values ('Handmade');

insert into PRODUCT_CATEGORY_TYPE (TYPE) 
values ('Body part');

create table PRODUCT_CATEGORY (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  CATEGORY varchar(100),
  CATEGORY_TYPE INT(11) unsigned,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID),
  CONSTRAINT PRODUCT_CATEGORY_ibfk_1 FOREIGN KEY (CATEGORY_TYPE) REFERENCES PRODUCT_CATEGORY_TYPE (ID)
);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Gold 5%', 1);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Gold 1%', 1);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Bead', 1);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Yes', 2);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('No', 2);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Neck', 3);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Temple', 3);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Hands', 3);

create table PRODUCT (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  NAME varchar(100),
  DISPLAY_ID varchar(10),
  PRICE decimal(10,2) NOT NULL,
  DISPLAY_PRICE decimal(10,2),
  DISCOUNT int(2) DEFAULT 0,
  RATINGS int(2) DEFAULT 0,
  IMAGE_URL varchar(255) NOT NULL,
  DESCRIPTION JSON NOT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID)
);


insert into PRODUCT (NAME, DISPLAY_ID, PRICE, DISPLAY_PRICE, DISCOUNT, DESCRIPTION, IMAGE_URL) 
values ('Necklace 1', 'ABcfdr', 450, 500, 10, '["a","b"]', '');

insert into PRODUCT (NAME, DISPLAY_ID, PRICE, DISPLAY_PRICE, DISCOUNT, DESCRIPTION, IMAGE_URL) 
values ('Necklace 5% gold', 'tBcfdr', 24550, 30000, 10, '["lorem ipsum","dolor sit amet","lorem ipsum dolor sit amet"]', '');

create table PRODUCT_CATERGORY_MAPPING (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  CATEGORY_ID int(11) unsigned NOT NULL,
  PRODUCT_ID int(11) unsigned NOT NULL,
  primary key (ID),
  CONSTRAINT PRODUCT_CATERGORY_MAPPING_ibfk_1 FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (ID),
  CONSTRAINT PRODUCT_CATERGORY_MAPPING_ibfk_2 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (1,1);
insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (4,1);
insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (6,1);


insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (1,2);
insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (5,2);
insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (6,2);


create table PRODUCT_AVAILABILITY (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  PRODUCT_ID int(11) unsigned,
  QTY int(11),
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID),
  CONSTRAINT PRODUCT_AVAILABILITY_ibfk_1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);