create table USER (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  FIRST_NAME varchar(100),
  LAST_NAME varchar(100),
  MOBILE varchar(12) NOT NULL,
  EMAIL varchar(255),
  OTP_VERIFIED tinyint DEFAULT 0,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID)
);

insert into USER (FIRST_NAME, LAST_NAME, MOBILE, EMAIL) 
values ('GANESH','Jadhav','9920566922','ganesh@ganesh.com');

create table PRODUCT_CATEGORY_TYPE (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  TYPE varchar(100),
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID)
);

insert into PRODUCT_CATEGORY_TYPE (TYPE) 
values ('Material');

insert into PRODUCT_CATEGORY_TYPE (TYPE) 
values ('Handmade');

insert into PRODUCT_CATEGORY_TYPE (TYPE) 
values ('Body part');

create table PRODUCT_CATEGORY (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  CATEGORY varchar(100),
  CATEGORY_TYPE INT(11) unsigned,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID),
  CONSTRAINT PRODUCT_CATEGORY_ibfk_1 FOREIGN KEY (CATEGORY_TYPE) REFERENCES PRODUCT_CATEGORY_TYPE (ID)
);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Gold 5%', 1);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Gold 1%', 1);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Bead', 1);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Yes', 2);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('No', 2);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Neck', 3);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Temple', 3);

insert into PRODUCT_CATEGORY (CATEGORY, CATEGORY_TYPE) 
values ('Hands', 3);

create table PRODUCT (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  NAME varchar(100),
  DISPLAY_ID varchar(10),
  PRICE decimal(10,2) NOT NULL,
  DISPLAY_PRICE decimal(10,2),
  DISCOUNT int(2) DEFAULT 0,
  RATINGS int(2) DEFAULT 0,
  IMAGE_URL varchar(255) NOT NULL,
  DESCRIPTION JSON NOT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID)
);

ALTER TABLE PRODUCT RENAME COLUMN PRICE TO SELLING_PRICE_AT;
ALTER TABLE PRODUCT ADD COLUMN TAX_AMOUNT decimal(10,2) unsigned NOT NULL DEFAULT 0;
ALTER TABLE PRODUCT ADD COLUMN TAX_PERCENT decimal(4,2) unsigned NOT NULL DEFAULT 0;
ALTER TABLE PRODUCT ADD COLUMN SELLING_PRICE_BT decimal(10,2) unsigned NOT NULL DEFAULT 0;
ALTER TABLE PRODUCT MODIFY COLUMN TAX_PERCENT decimal(4,2) unsigned NOT NULL DEFAULT 0;

insert into PRODUCT (NAME, DISPLAY_ID, PRICE, DISPLAY_PRICE, DISCOUNT, DESCRIPTION, IMAGE_URL) 
values ('Necklace 1', 'ABcfdr', 450, 500, 10, '["a","b"]', '');

update PRODUCT
set IMAGE_URL="https://storage.cloud.google.com/myfirstprojecttestecom/productimages/51lndCdP7uL._SX679_.jpg?authuser=1"
where ID=1;

update PRODUCT
set 
TAX_AMOUNT=50,
TAX_PERCENT=10,
SELLING_PRICE_BT=400
where ID=1;

insert into PRODUCT (NAME, DISPLAY_ID, SELLING_PRICE_AT, DISPLAY_PRICE, DISCOUNT, DESCRIPTION, IMAGE_URL) 
values ('Necklace 5% gold', 'tBcfdr', 24550, 30000, 10, '["lorem ipsum","dolor sit amet","lorem ipsum dolor sit amet"]', '');

update PRODUCT
set IMAGE_URL="https://storage.cloud.google.com/myfirstprojecttestecom/productimages/Screenshot%202021-11-11%20at%205.49.31%20PM.png?authuser=1"
where ID=2;

update PRODUCT
set 
TAX_AMOUNT=550,
TAX_PERCENT=10,
SELLING_PRICE_BT=24000
where ID=2;

insert into PRODUCT (NAME, DISPLAY_ID, SELLING_PRICE_AT, DISPLAY_PRICE, DISCOUNT, DESCRIPTION, IMAGE_URL, TAX_AMOUNT, TAX_PERCENT, SELLING_PRICE_BT) 
values ('1% gold bangles', 'tBffdg', 14550, 18000, 10, '["lorem ipsum","dolor sit amet","lorem ipsum dolor sit amet"]',
'https://storage.cloud.google.com/myfirstprojecttestecom/productimages/51lndCdP7uL._SX679_.jpg?authuser=1', 3550, 16, 11000);

insert into PRODUCT_AVAILABILITY (PRODUCT_ID, QTY)
values (3,9);

insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (2,3);
insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (4,3);
insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (8,3);

create table PRODUCT_CATERGORY_MAPPING (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  CATEGORY_ID int(11) unsigned NOT NULL,
  PRODUCT_ID int(11) unsigned NOT NULL,
  primary key (ID),
  CONSTRAINT PRODUCT_CATERGORY_MAPPING_ibfk_1 FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (ID),
  CONSTRAINT PRODUCT_CATERGORY_MAPPING_ibfk_2 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (1,1);
insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (4,1);
insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (6,1);


insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (1,2);
insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (5,2);
insert into PRODUCT_CATERGORY_MAPPING (CATEGORY_ID, PRODUCT_ID)
values (6,2);


create table PRODUCT_AVAILABILITY (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  PRODUCT_ID int(11) unsigned,
  QTY int(11),
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID),
  CONSTRAINT PRODUCT_AVAILABILITY_ibfk_1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

insert into PRODUCT_AVAILABILITY (PRODUCT_ID, QTY)
values (1,9);
insert into PRODUCT_AVAILABILITY (PRODUCT_ID, QTY)
values (2,0);


create table CART (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  USER_ID int(11) unsigned NOT NULL,
  STATUS enum('ACTIVE'),
  PAYABLE_AMOUNT decimal(10,2) DEFAULT 0,
  TOTAL_TAX_AMOUNT decimal(10,2) unsigned NOT NULL DEFAULT 0,
  TOTAL_SELLING_PRICE_BT decimal(10,2) NOT NULL DEFAULT 0,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID),
  CONSTRAINT CART_ibfk_1 FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

create table CART_ITEM (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  CART_ID int(11) unsigned NOT NULL,
  USER_ID int(11) unsigned NOT NULL,
  PRODUCT_ID int(11) unsigned NOT NULL,
  NAME varchar(100),
  SELLING_PRICE_AT decimal(10,2) unsigned NOT NULL,
  TAX_AMOUNT decimal(10,2) unsigned NOT NULL,
  TAX_PERCENT decimal(4,2) unsigned NOT NULL,
  SELLING_PRICE_BT decimal(10,2) NOT NULL,
  DISPLAY_PRICE decimal(10,2),
  IMAGE_URL varchar(255) NOT NULL,
  QTY int(11) unsigned NOT NULL DEFAULT 1,
  DESCRIPTION JSON NOT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID),
  CONSTRAINT CART_ITEMS_ibfk_1 FOREIGN KEY (CART_ID) REFERENCES CART (ID),
  CONSTRAINT CART_ITEMS_ibfk_2 FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);

ALTER TABLE CART_ITEM MODIFY COLUMN TAX_PERCENT decimal(4,2) unsigned NOT NULL DEFAULT 0;

create table CART_SNAPSHOT (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  USER_ID int(11) unsigned NOT NULL,
  ORDER_ID int(11) unsigned NOT NULL,
  STATUS enum('ACTIVE', 'VERIFICATION_PENDING', 'VERIFIED'),
  TOTAL_AMOUNT decimal(10,2) DEFAULT 0,
  PAID_AMOUNT decimal(10,2) DEFAULT 0,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID),
  CONSTRAINT CART_SNAPSHOT_ibfk_1 FOREIGN KEY (CART_ID) REFERENCES CART (ID)
);

create table PLACED_ORDERS (
  ID INT(11) unsigned NOT NULL AUTO_INCREMENT,
  PRODUCT_ID int(11) unsigned,
  QTY int(11),
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_AT timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  primary key (ID),
  CONSTRAINT PRODUCT_AVAILABILITY_ibfk_1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);